### First lab figures

This SQL is to query GL bleeding and Septic shock patients' data for subgroup study

In [1]:
import functools
import numpy as np
import pandas as pd
from scipy.stats import kstest
import matplotlib.pyplot as plt
import pylab as pl
import psycopg2
%matplotlib inline
plt.style.use('ggplot')

In [2]:
# create a database connection
sqluser = 'mimic'
dbname = 'mimic'
schema_name = 'mimiciii'

## Lab ranges

'Normal' ranges for lab values:

Lab Value	|  Lower limit	|  Upper Limit	|  Units
--- | --- | --- | ---
Bicarbonate	| 22	| 32	| mEq/L
BUN	| 6	| 20 | mEq/L
Calcium	| 8.4	| 10.3	| mg/dL
Chloride	| 96	| 108	| mEq/L
Creatinine	| 0.4	| 1.1	| mEq/L
Hemoglobin	| 11.2	 | 15.7	| g/dL
Lactate	| 0.5	| 2	| mmol/L
Magnesium	| 1.6	| 2.6	| mg/dL
Phosphate	| 2.7	| 4.5	| mg/dL
Platelet count	| 150	| 400	| K/uL
Potassium	| 3.3	| 5.1	| mEq/L
Sodium	| 133	| 145	| mEq/L

In [3]:
# Create dictionary of ranges
# Keys should match the lab names in the query below
# Are these values correct given the units? Need to check.

lab_ranges = {'BICARBONATE': [22,32],
              'BUN': [6,20],
              'CALCIUM': [8.4,10.3],
              'CHLORIDE': [96,108],
              'CREATININE': [0.4,1.1],
              'HEMOGLOBIN': [11.2,15.7],
              'LACTATE': [0.5,2.0],
              'MAGNESIUM': [1.6,2.6],
              'PHOSPHATE': [2.7,4.5],
              'PLATELET': [150,400],
              'POTASSIUM': [3.3,5.1],
              'SODIUM': [133,145],
              'FREECALCIUM': [4.64, 5.28]
             }

### SQL: get first laboratory measurements

[Gastrointestinal bleeding](https://en.wikipedia.org/wiki/Gastrointestinal_bleeding): ICD-9 code 578.9  
In MIMIC-III, the description is as follow:   

ICD 9 codes|short description|long description  
--- | --- | --- | ---
    5789| Gastrointest hemorr NOS | Hemorrhage of gastrointestinal tract, unspecified

In [20]:
con = psycopg2.connect(dbname=dbname, user=sqluser, password='mimic')
cur = con.cursor()
cur.execute('SET search_path to ' + schema_name)

query = \
"""
WITH gi_bleeding_group as
(
    SELECT subject_id, hadm_id,
        CASE
        -- Acute Organ Dysfunction Diagnosis Codes
        WHEN substring(icd9_code,1,4) IN ('5789') THEN 1
        ELSE 0 END AS gi_bleeding
        -- Explicit diagnosis of severe sepsis or septic shock
    FROM diagnoses_icd
), 

infection_group AS
(
    SELECT subject_id, hadm_id,
    CASE
        WHEN substring(icd9_code,1,3) IN ('001','002','003','004','005','008',
               '009','010','011','012','013','014','015','016','017','018',
               '020','021','022','023','024','025','026','027','030','031',
               '032','033','034','035','036','037','038','039','040','041',
               '090','091','092','093','094','095','096','097','098','100',
               '101','102','103','104','110','111','112','114','115','116',
               '117','118','320','322','324','325','420','421','451','461',
               '462','463','464','465','481','482','485','486','494','510',
               '513','540','541','542','566','567','590','597','601','614',
               '615','616','681','682','683','686','730') THEN 1
        WHEN substring(icd9_code,1,4) IN ('5695','5720','5721','5750','5990','7110',
                '7907','9966','9985','9993') THEN 1
        WHEN substring(icd9_code,1,5) IN ('49121','56201','56203','56211','56213',
                '56983') THEN 1
        ELSE 0 END AS infection
    FROM diagnoses_icd
),
-- ICD-9 codes for organ dysfunction - as sourced from Appendix 2 of above paper
organ_diag_group as
(
    SELECT subject_id, hadm_id,
        CASE
        -- Acute Organ Dysfunction Diagnosis Codes
        WHEN substring(icd9_code,1,3) IN ('458','293','570','584') THEN 1
        WHEN substring(icd9_code,1,4) IN ('7855','3483','3481',
                '2874','2875','2869','2866','5734')  THEN 1
        ELSE 0 END AS organ_dysfunction,
        -- Explicit diagnosis of severe sepsis or septic shock
        CASE
        WHEN substring(icd9_code,1,5) IN ('99592','78552')  THEN 1
        ELSE 0 END AS explicit_sepsis
    FROM diagnoses_icd
),
-- Mechanical ventilation
organ_proc_group as
(
    SELECT subject_id, hadm_id,
        CASE
        WHEN substring(icd9_code,1,4) IN ('9670','9671','9672') THEN 1
        ELSE 0 END AS mech_vent
    FROM procedures_icd
),
-- Aggregate above views together
aggregate as
(
    SELECT subject_id, hadm_id,
        CASE
            WHEN hadm_id in
                    (SELECT DISTINCT hadm_id
                    FROM infection_group
                    WHERE infection = 1)
                THEN 1
            ELSE 0 END AS infection,
        CASE
            WHEN hadm_id in
                    (SELECT DISTINCT hadm_id
                    FROM organ_diag_group
                    WHERE explicit_sepsis = 1)
                THEN 1
            ELSE 0 END AS explicit_sepsis,
        CASE
            WHEN hadm_id in
                    (SELECT DISTINCT hadm_id
                    FROM organ_diag_group
                    WHERE organ_dysfunction = 1)
                THEN 1
            ELSE 0 END AS organ_dysfunction,
        CASE
        WHEN hadm_id in
                (SELECT DISTINCT hadm_id
                FROM organ_proc_group
                WHERE mech_vent = 1)
            THEN 1
        ELSE 0 END AS mech_vent
    FROM admissions
),

pvt AS (
  SELECT ie.subject_id, ie.hadm_id, ie.outtime, ie.icustay_id, le.charttime, ad.deathtime, ie.los, gi.gi_bleeding
  , ROUND((cast(ad.admittime as date) - cast(p.dob as date)) / 365.242, 2) as first_admit_age
  , CASE when ad.deathtime between ie.intime and ie.outtime THEN 1 ELSE 0 END AS mort_icu
  , CASE when ad.deathtime between ad.admittime and ad.dischtime THEN 1 ELSE 0 END AS mort_hosp
  -- here we assign labels to ITEMIDs
  -- this also fuses together multiple ITEMIDs containing the same data
  , CASE
        WHEN ag.explicit_sepsis = 1 THEN 1
        WHEN ag.infection = 1 AND ag.organ_dysfunction = 1 THEN 1
        WHEN ag.infection = 1 AND ag.mech_vent = 1 THEN 1
        ELSE 0 END
    AS angus
  , CASE
        when itemid = 50811 then 'HEMOGLOBIN'
        when itemid = 51222 then 'HEMOGLOBIN'
        when itemid = 50813 then 'LACTATE'
        -- Free calcium
        when itemid = 50808 then 'FREECALCIUM'
      ELSE null
      END AS label
  , -- add in some sanity checks on the values
    -- the where clause below requires all valuenum to be > 0,
    -- so these are only upper limit checks
    CASE
      when le.itemid = 50811 and le.valuenum >    50 then null -- g/dL 'HEMOGLOBIN'
      when le.itemid = 51222 and le.valuenum >    50 then null -- g/dL 'HEMOGLOBIN'
      when le.itemid = 50813 and le.valuenum >    50 then null -- mmol/L 'LACTATE'
      -- Free Calcium
      when le.itemid = 50808 and le.valuenum > 500 then null
    ELSE le.valuenum
    END AS valuenum
  FROM icustays ie

  LEFT JOIN labevents le
    ON le.subject_id = ie.subject_id
    AND le.hadm_id = ie.hadm_id
    AND le.charttime between (ie.intime - interval '24' hour)
    AND (ie.intime + interval '24' hour)
    AND le.itemid IN
    (
      -- comment is: LABEL | CATEGORY | FLUID | NUMBER OF ROWS IN LABEVENTS
      51222, -- HEMOGLOBIN | HEMATOLOGY | BLOOD | 752523
      50811, -- HEMOGLOBIN | BLOOD GAS | BLOOD | 89712
      50813, -- LACTATE | BLOOD GAS | BLOOD | 187124
      -- Free calcium
      50808  --FREE CALCIUM | NA | NA | NA
    )
    AND le.valuenum IS NOT null
    AND le.valuenum > 0 -- lab values cannot be 0 and cannot be negative

    LEFT JOIN admissions ad
    ON ie.subject_id = ad.subject_id
    AND ie.hadm_id = ad.hadm_id
    
    LEFT JOIN gi_bleeding_group gi
    ON ie.subject_id = gi.subject_id
    AND ie.hadm_id = gi.hadm_id
    
    LEFT JOIN aggregate ag
    ON ie.subject_id = ag.subject_id
    AND ie.hadm_id = ag.hadm_id
    
    INNER JOIN patients p
    ON ie.subject_id = p.subject_id
    WHERE ROUND((cast(ad.admittime as date) - cast(p.dob as date)) / 365.242, 2) > 15
    -- WHERE ie.subject_id < 10000
),
ranked AS (
SELECT pvt.*, DENSE_RANK() OVER (PARTITION BY
    pvt.subject_id, pvt.hadm_id, pvt.icustay_id, pvt.label ORDER BY cast(pvt.charttime as date)) as drank
FROM pvt
)

SELECT r.subject_id, r.hadm_id, r.icustay_id, r.mort_icu, r.mort_hosp
  -- , max(r.hadm_id) as HADM_ID
  -- , max(r.icustay_id) as ICUSTAY_ID
  , max(r.gi_bleeding) as GI_BLEEDING
  , max(r.angus) as ANGUS
  , max(r.los) as LOS
  , max(r.mort_icu) as MORT_ICU
  , max(r.mort_hosp) as MORT_HOSP
  , max(r.first_admit_age) as FIRST_ADMIT_AGE
  , max(r.charttime) as CHARTTIME
  , max(case when label = 'HEMOGLOBIN' then valuenum else null end) as HEMOGLOBIN_1st
  , max(case when label = 'LACTATE' then valuenum else null end) as LACTATE_1st
  , max(case when label = 'FREECALCIUM' then valuenum else null end) as FREECALCIUM_1st
FROM ranked r
WHERE r.drank = 1
GROUP BY r.subject_id, r.hadm_id, r.icustay_id, r.mort_icu, r.mort_hosp, r.drank
ORDER BY r.subject_id, r.hadm_id, r.icustay_id, r.mort_icu, r.mort_hosp, r.drank;
"""
    
data = pd.read_sql_query(query,con)

In [23]:
print data.shape
print data
#print data[data.gi_bleeding == 1].shape
#print data[data.gi_bleeding == 0].shape

(53431, 15)
       subject_id  hadm_id  icustay_id  mort_icu  mort_hosp  gi_bleeding  \
0               3   145834      211552         0          0            0
1               4   185777      294638         0          0            0
2               6   107064      228232         0          0            0
3               9   150750      220597         1          1            0
4              11   194540      229441         0          0            0
5              12   112213      232669         0          1            0
6              13   143045      263738         0          0            0
7              17   161087      257980         0          0            0
8              17   194023      277042         0          0            0
9              18   188822      298129         0          0            0
10             19   109235      273430         0          0            0
11             20   157681      264490         0          0            0
12             21   109451      217847         0          0            1
13             21   111970      216859         1          1            0
14             22   165315      204798         0          0            0
15             23   124321      234044         0          0            0
16             23   152223      227807         0          0            0
17             24   161859      262236         0          0            0
18             25   129635      203487         0          0            0
19             26   197661      244882         0          0            0
20             28   162569      225559         0          0            0
21             30   104557      225176         0          0            0
22             31   128652      254478         1          1            0
23             32   175413      295037         0          0            0
24             33   176176      296681         0          0            0
25             34   115799      263086         0          0            0
26             34   144319      290505         0          0            0
27             35   166707      282039         0          0            0
28             36   122659      211200         0          0            0
29             36   165660      241249         0          0            0
...           ...      ...         ...       ...        ...          ...
53401       99901   131711      226541         0          0            0
53402       99903   135939      291066         0          0            0
53403       99912   189380      236183         0          0            0
53404       99913   175989      292375         0          0            0
53405       99922   123563      259919         0          0            0
53406       99923   164914      202505         0          0            0
53407       99923   192053      298857         0          0            0
53408       99928   104802      236704         0          0            0
53409       99934   176121      291007         0          0            0
53410       99935   174624      255381         1          1            0
53411       99936   107913      213906         0          0            0
53412       99937   129380      291004         0          0            0
53413       99938   103815      296707         0          0            0
53414       99939   159023      252442         0          0            0
53415       99944   185654      221067         0          0            1
53416       99946   157197      298613         0          0            0
53417       99955   108494      243255         1          1            0
53418       99957   148574      257127         0          0            0
53419       99965   101083      257338         0          0            0
53420       99966   167228      252173         0          0            0
53421       99973   150202      275083         0          0            0
53422       99982   112748      275958         0          0            0
53423       99982   151454      221194         0          0            0
53424       99982   183791      239827         0          0            0
53425       99983   117390      286606         0          0            0
53426       99985   176670      279638         0          0            0
53427       99991   151118      226241         0          0            0
53428       99992   197084      242052         0          0            0
53429       99995   137810      229633         0          0            0
53430       99999   113369      246512         0          0            0

       angus      los  mort_icu  mort_hosp  first_admit_age  \
0          1   6.0646         0          0            76.52
1          0   1.6785         0          0            47.84
2          0   3.6729         0          0            65.94
3          0   5.3231         1          1            41.79
4          0   1.5844         0          0            50.15
5          0   7.6348         0          1            72.37
6          0   3.6660         0          0            39.86
7          0   0.8795         0          0            47.82
8          0   2.0710         0          0            47.45
9          0   1.2885         0          0            50.84
10         0   1.3017         0          0           300.00
11         0   1.0508         0          0            75.88
12         1   5.9017         0          0            87.44
13         1   8.3647         1          1            87.82
14         0   1.1438         0          0            64.93
15         0   1.1862         0          0            75.25
16         0   1.2641         0          0            71.13
17         0   0.5124         0          0            39.02
18         0   3.5466         0          0            58.95
19         0   2.1407         0          0            72.00
20         0   1.1224         0          0            74.38
21         0   1.8472         0          0           300.00
22         1   7.9379         1          1            72.26
23         0   7.6854         0          0            45.51
24         0   1.5542         0          0            82.39
25         0   0.7198         0          0           300.00
26         0   1.5824         0          0           304.60
27         0   5.3757         0          0            69.44
28         0   6.8595         0          0            69.73
29         1   4.3483         0          0            72.73
...      ...      ...       ...        ...              ...
53401      1   6.1242         0          0            68.83
53402      0   1.0388         0          0            50.11
53403      1  12.0867         0          0            84.54
53404      0   3.1669         0          0            71.09
53405      0   1.0023         0          0            69.28
53406      0   0.7497         0          0            54.39
53407      0   2.2353         0          0            54.61
53408      0   0.9902         0          0            20.87
53409      0   3.5489         0          0            17.95
53410      0   0.6598         1          1            75.57
53411      0   3.8185         0          0           300.00
53412      0   1.1816         0          0            65.68
53413      0   7.2813         0          0            80.84
53414      1   2.8780         0          0            26.95
53415      0   4.0542         0          0            85.48
53416      0   0.7992         0          0            49.67
53417      0   5.6719         1          1            63.19
53418      0   2.8684         0          0            68.05
53419      0   1.7262         0          0            66.29
53420      0   1.7034         0          0            77.49
53421      1   2.7319         0          0            65.50
53422      0   4.9427         0          0            65.26
53423      0   7.9493         0          0            65.16
53424      0   6.1701         0          0            65.38
53425      0   1.0399         0          0            78.58
53426      1  11.2998         0          0            53.81
53427      1   3.1426         0          0            47.72
53428      0   1.9745         0          0            65.77
53429      0   2.1615         0          0            88.70
53430      0   1.1242         0          0            63.98

                charttime  hemoglobin_1st  lactate_1st  freecalcium_1st
0     2101-10-20 21:51:00            10.3          8.8             1.09
1     2191-03-15 21:23:00            11.5          2.1              NaN
2     2175-05-30 16:08:00             9.9          3.9             1.27
3     2149-11-09 19:42:00            15.4          2.7             0.99
4     2178-04-15 20:40:00            12.5          NaN              NaN
5     2104-08-07 21:51:00            12.8          4.0             1.20
6     2167-01-09 17:14:00            12.3          NaN             1.34
7     2135-05-09 20:52:00            12.3          NaN             1.22
8     2134-12-27 19:32:00            13.7          NaN             1.32
9     2167-10-02 10:44:00            14.8          3.6             1.16
10    2108-08-05 07:18:00            14.9          2.7              NaN
11    2183-04-28 20:41:00            11.8          NaN             1.18
12    2134-09-12 20:13:00             9.7          3.9             1.27
13    2135-01-30 19:18:00             9.1          1.6              NaN
14    2196-04-09 10:14:00            12.2          NaN              NaN
15    2157-10-21 13:40:00            14.5          4.6             1.07
16    2153-09-03 20:38:00            11.2          NaN             1.21
17    2139-06-06 13:46:00            14.7          NaN              NaN
18    2160-11-02 13:26:00            13.1          1.8             1.17
19    2126-05-08 04:00:00            12.2          NaN              NaN
20    2177-09-01 18:31:00            13.6          NaN             1.20
21    2172-10-14 20:30:00             9.5          NaN              NaN
22    2108-08-23 16:12:00            10.6          1.5             1.12
23    2170-04-04 18:54:00            11.7          NaN             0.99
24    2116-12-23 23:53:00            14.7          6.0              NaN
25    2186-07-18 18:12:00            13.7          NaN              NaN
26    2191-02-23 10:48:00            11.9          1.7             1.10
27    2122-02-10 21:54:00            12.6          NaN             1.25
28    2131-05-16 21:56:00             8.9          3.7             1.01
29    2134-05-12 17:48:00            14.5          1.0              NaN
...                   ...             ...          ...              ...
53401 2173-01-12 07:30:00             9.6          NaN              NaN
53402 2146-01-06 17:30:00            14.9          NaN              NaN
53403 2153-04-13 21:54:00            16.1          7.9             1.05
53404 2141-05-12 19:04:00            14.5          2.5             1.24
53405 2107-04-07 14:43:00            12.2          3.8             1.16
53406 2201-02-23 23:21:00            11.1          NaN              NaN
53407 2201-05-15 23:32:00            12.7          1.8             1.11
53408 2181-11-16 15:13:00            14.6          1.7              NaN
53409 2110-02-28 04:05:00            11.3          NaN              NaN
53410 2139-12-15 05:59:00            16.4          2.5             1.13
53411 2182-10-10 10:35:00            13.8          1.6             1.11
53412 2128-05-11 11:11:00            13.4          3.6              NaN
53413 2200-10-27 22:04:00            10.6          1.7             1.18
53414 2110-03-22 20:58:00             8.6          1.8             0.95
53415 2161-02-16 22:01:00            10.4          1.0              NaN
53416 2161-07-14 16:47:00            18.1          2.1              NaN
53417 2139-07-14 04:18:00            15.8          NaN             1.08
53418 2157-02-20 23:38:00            13.0          2.1             1.12
53419 2191-07-13 17:32:00            12.1          NaN              NaN
53420 2191-08-23 21:38:00            12.6          1.6              NaN
53421 2180-11-26 21:46:00             9.6          0.9              NaN
53422 2157-01-06 07:25:00            11.1          NaN              NaN
53423 2156-11-29 11:03:00            10.6          2.5             1.14
53424 2157-02-16 18:45:00            11.9          NaN              NaN
53425 2193-04-26 14:15:00            13.6          NaN              NaN
53426 2181-01-29 08:57:00            10.9          2.1              NaN
53427 2184-12-28 22:05:00            12.1          2.2              NaN
53428 2144-07-25 13:20:00             4.8          NaN              NaN
53429 2147-02-08 15:07:00             9.0          1.5             1.12
53430 2117-12-31 07:10:00             8.7          NaN              NaN

[53431 rows x 15 columns]

In [24]:
data.to_csv('subgroup_data.csv')

#### From initial to first lab measurements (to be updated)

In [25]:
data_initial = pd.read_csv("subgroup_data.csv", index_col=0)

In [26]:
data_final = data_initial.groupby('subject_id').apply(lambda x: x.sort_values('charttime')).reset_index(drop=True)

In [27]:
print data_final

       subject_id  hadm_id  icustay_id  mort_icu  mort_hosp  gi_bleeding  \
0               3   145834      211552         0          0            0
1               4   185777      294638         0          0            0
2               6   107064      228232         0          0            0
3               9   150750      220597         1          1            0
4              11   194540      229441         0          0            0
5              12   112213      232669         0          1            0
6              13   143045      263738         0          0            0
7              17   194023      277042         0          0            0
8              17   161087      257980         0          0            0
9              18   188822      298129         0          0            0
10             19   109235      273430         0          0            0
11             20   157681      264490         0          0            0
12             21   109451      217847         0          0            1
13             21   111970      216859         1          1            0
14             22   165315      204798         0          0            0
15             23   152223      227807         0          0            0
16             23   124321      234044         0          0            0
17             24   161859      262236         0          0            0
18             25   129635      203487         0          0            0
19             26   197661      244882         0          0            0
20             28   162569      225559         0          0            0
21             30   104557      225176         0          0            0
22             31   128652      254478         1          1            0
23             32   175413      295037         0          0            0
24             33   176176      296681         0          0            0
25             34   115799      263086         0          0            0
26             34   144319      290505         0          0            0
27             35   166707      282039         0          0            0
28             36   182104      280987         0          0            0
29             36   122659      211200         0          0            0
...           ...      ...         ...       ...        ...          ...
53401       99901   131711      226541         0          0            0
53402       99903   135939      291066         0          0            0
53403       99912   189380      236183         0          0            0
53404       99913   175989      292375         0          0            0
53405       99922   123563      259919         0          0            0
53406       99923   164914      202505         0          0            0
53407       99923   192053      298857         0          0            0
53408       99928   104802      236704         0          0            0
53409       99934   176121      291007         0          0            0
53410       99935   174624      255381         1          1            0
53411       99936   107913      213906         0          0            0
53412       99937   129380      291004         0          0            0
53413       99938   103815      296707         0          0            0
53414       99939   159023      252442         0          0            0
53415       99944   185654      221067         0          0            1
53416       99946   157197      298613         0          0            0
53417       99955   108494      243255         1          1            0
53418       99957   148574      257127         0          0            0
53419       99965   101083      257338         0          0            0
53420       99966   167228      252173         0          0            0
53421       99973   150202      275083         0          0            0
53422       99982   151454      221194         0          0            0
53423       99982   112748      275958         0          0            0
53424       99982   183791      239827         0          0            0
53425       99983   117390      286606         0          0            0
53426       99985   176670      279638         0          0            0
53427       99991   151118      226241         0          0            0
53428       99992   197084      242052         0          0            0
53429       99995   137810      229633         0          0            0
53430       99999   113369      246512         0          0            0

       angus      los  mort_icu.1  mort_hosp.1  first_admit_age  \
0          1   6.0646           0            0            76.52
1          0   1.6785           0            0            47.84
2          0   3.6729           0            0            65.94
3          0   5.3231           1            1            41.79
4          0   1.5844           0            0            50.15
5          0   7.6348           0            1            72.37
6          0   3.6660           0            0            39.86
7          0   2.0710           0            0            47.45
8          0   0.8795           0            0            47.82
9          0   1.2885           0            0            50.84
10         0   1.3017           0            0           300.00
11         0   1.0508           0            0            75.88
12         1   5.9017           0            0            87.44
13         1   8.3647           1            1            87.82
14         0   1.1438           0            0            64.93
15         0   1.2641           0            0            71.13
16         0   1.1862           0            0            75.25
17         0   0.5124           0            0            39.02
18         0   3.5466           0            0            58.95
19         0   2.1407           0            0            72.00
20         0   1.1224           0            0            74.38
21         0   1.8472           0            0           300.00
22         1   7.9379           1            1            72.26
23         0   7.6854           0            0            45.51
24         0   1.5542           0            0            82.39
25         0   0.7198           0            0           300.00
26         0   1.5824           0            0           304.60
27         0   5.3757           0            0            69.44
28         0   1.1096           0            0            69.70
29         0   6.8595           0            0            69.73
...      ...      ...         ...          ...              ...
53401      1   6.1242           0            0            68.83
53402      0   1.0388           0            0            50.11
53403      1  12.0867           0            0            84.54
53404      0   3.1669           0            0            71.09
53405      0   1.0023           0            0            69.28
53406      0   0.7497           0            0            54.39
53407      0   2.2353           0            0            54.61
53408      0   0.9902           0            0            20.87
53409      0   3.5489           0            0            17.95
53410      0   0.6598           1            1            75.57
53411      0   3.8185           0            0           300.00
53412      0   1.1816           0            0            65.68
53413      0   7.2813           0            0            80.84
53414      1   2.8780           0            0            26.95
53415      0   4.0542           0            0            85.48
53416      0   0.7992           0            0            49.67
53417      0   5.6719           1            1            63.19
53418      0   2.8684           0            0            68.05
53419      0   1.7262           0            0            66.29
53420      0   1.7034           0            0            77.49
53421      1   2.7319           0            0            65.50
53422      0   7.9493           0            0            65.16
53423      0   4.9427           0            0            65.26
53424      0   6.1701           0            0            65.38
53425      0   1.0399           0            0            78.58
53426      1  11.2998           0            0            53.81
53427      1   3.1426           0            0            47.72
53428      0   1.9745           0            0            65.77
53429      0   2.1615           0            0            88.70
53430      0   1.1242           0            0            63.98

                 charttime  hemoglobin_1st  lactate_1st  freecalcium_1st
0      2101-10-20 21:51:00            10.3          8.8             1.09
1      2191-03-15 21:23:00            11.5          2.1              NaN
2      2175-05-30 16:08:00             9.9          3.9             1.27
3      2149-11-09 19:42:00            15.4          2.7             0.99
4      2178-04-15 20:40:00            12.5          NaN              NaN
5      2104-08-07 21:51:00            12.8          4.0             1.20
6      2167-01-09 17:14:00            12.3          NaN             1.34
7      2134-12-27 19:32:00            13.7          NaN             1.32
8      2135-05-09 20:52:00            12.3          NaN             1.22
9      2167-10-02 10:44:00            14.8          3.6             1.16
10     2108-08-05 07:18:00            14.9          2.7              NaN
11     2183-04-28 20:41:00            11.8          NaN             1.18
12     2134-09-12 20:13:00             9.7          3.9             1.27
13     2135-01-30 19:18:00             9.1          1.6              NaN
14     2196-04-09 10:14:00            12.2          NaN              NaN
15     2153-09-03 20:38:00            11.2          NaN             1.21
16     2157-10-21 13:40:00            14.5          4.6             1.07
17     2139-06-06 13:46:00            14.7          NaN              NaN
18     2160-11-02 13:26:00            13.1          1.8             1.17
19     2126-05-08 04:00:00            12.2          NaN              NaN
20     2177-09-01 18:31:00            13.6          NaN             1.20
21     2172-10-14 20:30:00             9.5          NaN              NaN
22     2108-08-23 16:12:00            10.6          1.5             1.12
23     2170-04-04 18:54:00            11.7          NaN             0.99
24     2116-12-23 23:53:00            14.7          6.0              NaN
25     2186-07-18 18:12:00            13.7          NaN              NaN
26     2191-02-23 10:48:00            11.9          1.7             1.10
27     2122-02-10 21:54:00            12.6          NaN             1.25
28     2131-05-04 20:45:00            12.6          NaN             1.21
29     2131-05-16 21:56:00             8.9          3.7             1.01
...                    ...             ...          ...              ...
53401  2173-01-12 07:30:00             9.6          NaN              NaN
53402  2146-01-06 17:30:00            14.9          NaN              NaN
53403  2153-04-13 21:54:00            16.1          7.9             1.05
53404  2141-05-12 19:04:00            14.5          2.5             1.24
53405  2107-04-07 14:43:00            12.2          3.8             1.16
53406  2201-02-23 23:21:00            11.1          NaN              NaN
53407  2201-05-15 23:32:00            12.7          1.8             1.11
53408  2181-11-16 15:13:00            14.6          1.7              NaN
53409  2110-02-28 04:05:00            11.3          NaN              NaN
53410  2139-12-15 05:59:00            16.4          2.5             1.13
53411  2182-10-10 10:35:00            13.8          1.6             1.11
53412  2128-05-11 11:11:00            13.4          3.6              NaN
53413  2200-10-27 22:04:00            10.6          1.7             1.18
53414  2110-03-22 20:58:00             8.6          1.8             0.95
53415  2161-02-16 22:01:00            10.4          1.0              NaN
53416  2161-07-14 16:47:00            18.1          2.1              NaN
53417  2139-07-14 04:18:00            15.8          NaN             1.08
53418  2157-02-20 23:38:00            13.0          2.1             1.12
53419  2191-07-13 17:32:00            12.1          NaN              NaN
53420  2191-08-23 21:38:00            12.6          1.6              NaN
53421  2180-11-26 21:46:00             9.6          0.9              NaN
53422  2156-11-29 11:03:00            10.6          2.5             1.14
53423  2157-01-06 07:25:00            11.1          NaN              NaN
53424  2157-02-16 18:45:00            11.9          NaN              NaN
53425  2193-04-26 14:15:00            13.6          NaN              NaN
53426  2181-01-29 08:57:00            10.9          2.1              NaN
53427  2184-12-28 22:05:00            12.1          2.2              NaN
53428  2144-07-25 13:20:00             4.8          NaN              NaN
53429  2147-02-08 15:07:00             9.0          1.5             1.12
53430  2117-12-31 07:10:00             8.7          NaN              NaN

[53431 rows x 15 columns]

In [28]:
data_final = data_final.groupby('subject_id').first().reset_index()

In [29]:
#print data_final
print data_final[data_final.gi_bleeding == 1].shape

(1718, 15)

In [30]:
data_final.to_csv('subgroup_data_final.csv')

In [4]:
con = psycopg2.connect(dbname=dbname, user=sqluser, password='mimic')
cur = con.cursor()
cur.execute('SET search_path to ' + schema_name)

query = \
"""
SELECT * FROM d_icd_diagnoses dd
"""

units = pd.read_sql_query(query,con)
print units

       row_id icd9_code               short_title  \
0         174     01166     TB pneumonia-oth test
1         175     01170    TB pneumothorax-unspec
2         176     01171   TB pneumothorax-no exam
3         177     01172  TB pneumothorx-exam unkn
4         178     01173  TB pneumothorax-micro dx
5         179     01174   TB pneumothorax-cult dx
6         180     01175  TB pneumothorax-histo dx
7         181     01176  TB pneumothorax-oth test
8         182     01180   Pulmonary TB NEC-unspec
9         183     01181  Pulmonary TB NEC-no exam
10        184     01182   Pulmon TB NEC-exam unkn
11        185     01183    Pulmon TB NEC-micro dx
12        186     01184     Pulmon TB NEC-cult dx
13        187     01185    Pulmon TB NEC-histo dx
14        188     01186    Pulmon TB NEC-oth test
15        189     01190   Pulmonary TB NOS-unspec
16        190     01191  Pulmonary TB NOS-no exam
17        191     01192   Pulmon TB NOS-exam unkn
18        192     01193    Pulmon TB NOS-micro dx
19        193     01194     Pulmon TB NOS-cult dx
20        194     01195    Pulmon TB NOS-histo dx
21        195     01196    Pulmon TB NOS-oth test
22        196     01200        TB pleurisy-unspec
23        197     01201       TB pleurisy-no exam
24        198     01202     TB pleurisy-exam unkn
25        199     01203      TB pleurisy-micro dx
26        200     01204       TB pleurisy-cult dx
27        201     01205   TB pleurisy-histolog dx
28        202     01206      TB pleurisy-oth test
29        203     01210  TB thoracic nodes-unspec
...       ...       ...                       ...
14537   14407     E9949  War inj:aircrft dest NOS
14538   14408     E9950    War inj:hnd-hnd combat
14539   14409     E9951      War inj:blunt object
14540   14410     E9952   War inj:piercing object
14541   14411     E9953  War inj:intn restrct air
14542   14412     E9954   War inj:unintentl drown
14543   14413     E9958   War inj:con warfare NEC
14544   14414     E9959   War inj:con warfare NOS
14545   14415     E9960   War inj:dir nucl weapon
14546   14416     E9961  War inj:indir nucl weapn
14547   14417     E9962  War inj:therml radiation
14548   14418     E9963   War inj:nuclear rad eff
14549   14419     E9968   War inj:nucl weapon NEC
14550   14420     E9969   War inj:nucl weapon NOS
14551   14421     E9970         War injury:lasers
14552   14422     E9971   War injury:biol warfare
14553   14423     E9972   War injury:gas/fum/chem
14554   14424     E9973           War inj:WMD NOS
14555   14425     E9978  War inj-unconven war NEC
14556   14426     E9979  War inj-unconven war NOS
14557   14427     E9980   War inj:expl mine-cease
14558   14428     E9981   War inj:expl bomb-cease
14559   14429     V7388  Scrn oth spcf chlmyd dis
14560   14430     V7389   Scrn oth spcf viral dis
14561   14431     V7398    Scrn unspcf chlmyd dis
14562   14432     V7399     Scrn unspcf viral dis
14563   14433      V740     Screening for cholera
14564   14434      V741    Screening-pulmonary TB
14565   14435      V742     Screening for leprosy
14566   14436      V743  Screening for diphtheria

                                              long_title
0      Tuberculous pneumonia [any form], tubercle bac...
1                  Tuberculous pneumothorax, unspecified
2      Tuberculous pneumothorax, bacteriological or h...
3      Tuberculous pneumothorax, bacteriological or h...
4      Tuberculous pneumothorax, tubercle bacilli fou...
5      Tuberculous pneumothorax, tubercle bacilli not...
6      Tuberculous pneumothorax, tubercle bacilli not...
7      Tuberculous pneumothorax, tubercle bacilli not...
8      Other specified pulmonary tuberculosis, unspec...
9      Other specified pulmonary tuberculosis, bacter...
10     Other specified pulmonary tuberculosis, bacter...
11     Other specified pulmonary tuberculosis, tuberc...
12     Other specified pulmonary tuberculosis, tuberc...
13     Other specified pulmonary tuberculosis, tuberc...
14     Other specified pulmonary tuberculosis, tuberc...
15      Pulmonary tuberculosis, unspecified, unspecified
16     Pulmonary tuberculosis, unspecified, bacteriol...
17     Pulmonary tuberculosis, unspecified, bacteriol...
18     Pulmonary tuberculosis, unspecified, tubercle ...
19     Pulmonary tuberculosis, unspecified, tubercle ...
20     Pulmonary tuberculosis, unspecified, tubercle ...
21     Pulmonary tuberculosis, unspecified, tubercle ...
22                     Tuberculous pleurisy, unspecified
23     Tuberculous pleurisy, bacteriological or histo...
24     Tuberculous pleurisy, bacteriological or histo...
25     Tuberculous pleurisy, tubercle bacilli found (...
26     Tuberculous pleurisy, tubercle bacilli not fou...
27     Tuberculous pleurisy, tubercle bacilli not fou...
28     Tuberculous pleurisy, tubercle bacilli not fou...
29     Tuberculosis of intrathoracic lymph nodes, uns...
...                                                  ...
14537  Injury due to war operations by unspecified de...
14538  Injury due to war operations by unarmed hand-t...
14539  Injury due to war operations, struck by blunt ...
14540    Injury due to war operations by piercing object
14541  Injury due to war operations by intentional re...
14542  Injury due to war operations by unintentional ...
14543  Injury due to war operations by other forms of...
14544  Injury due to war operations by unspecified fo...
14545  Injury due to war operations by direct blast e...
14546  Injury due to war operations by indirect blast...
14547  Injury due to war operations by thermal radiat...
14548  Injury due to war operations by nuclear radiat...
14549  Injury due to war operations by other effects ...
14550  Injury due to war operations by unspecified ef...
14551             Injury due to war operations by lasers
14552  Injury due to war operations by biological war...
14553  Injury due to war operations by gases, fumes, ...
14554  Injury due to war operations by weapon of mass...
14555  Injury due to other specified forms of unconve...
14556  Injury due to unspecified form of unconvention...
14557  Injury due to war operations but occurring aft...
14558  Injury due to war operations but occurring aft...
14559  Special screening examination for other specif...
14560  Special screening examination for other specif...
14561  Special screening examination for unspecified ...
14562  Special screening examination for unspecified ...
14563                  Screening examination for cholera
14564   Screening examination for pulmonary tuberculosis
14565  Screening examination for leprosy (Hansen's di...
14566               Screening examination for diphtheria

[14567 rows x 4 columns]

In [6]:
units.to_csv("D_diagnose_ICD.csv")