### First lab figures

In [23]:
import functools
import numpy as np
import pandas as pd
from scipy.stats import kstest
import matplotlib.pyplot as plt
import pylab as pl
import psycopg2
%matplotlib inline
plt.style.use('ggplot')

In [24]:
# create a database connection
sqluser = 'mimic'
dbname = 'mimic'
schema_name = 'mimiciii'

## Lab ranges

'Normal' ranges for lab values:

Lab Value	|  Lower limit	|  Upper Limit	|  Units
--- | --- | --- | ---
Bicarbonate	| 22	| 32	| mEq/L
BUN	| 6	| 20 | mEq/L
Calcium	| 8.4	| 10.3	| mg/dL
Chloride	| 96	| 108	| mEq/L
Creatinine	| 0.4	| 1.1	| mEq/L
Hemoglobin	| 11.2	 | 15.7	| g/dL
Lactate	| 0.5	| 2	| mmol/L
Magnesium	| 1.6	| 2.6	| mg/dL
Phosphate	| 2.7	| 4.5	| mg/dL
Platelet count	| 150	| 400	| K/uL
Potassium	| 3.3	| 5.1	| mEq/L
Sodium	| 133	| 145	| mEq/L

In [25]:
# Create dictionary of ranges
# Keys should match the lab names in the query below
# Are these values correct given the units? Need to check.

lab_ranges = {'BICARBONATE': [22,32],
              'BUN': [6,20],
              'CALCIUM': [8.4,10.3],
              'CHLORIDE': [96,108],
              'CREATININE': [0.4,1.1],
              'HEMOGLOBIN': [11.2,15.7],
              'LACTATE': [0.5,2.0],
              'MAGNESIUM': [1.6,2.6],
              'PHOSPHATE': [2.7,4.5],
              'PLATELET': [150,400],
              'POTASSIUM': [3.3,5.1],
              'SODIUM': [133,145],
              'FREECALCIUM': [4.64, 5.28]
             }

### SQL: get first laboratory measurements

In [26]:
con = psycopg2.connect(dbname=dbname, user=sqluser, password='mimic')
cur = con.cursor()
cur.execute('SET search_path to ' + schema_name)

query = \
"""
WITH pvt AS (
  SELECT ie.subject_id, ie.hadm_id, ie.outtime, ie.icustay_id, le.charttime, ad.deathtime, ie.los
  , ROUND((cast(ad.admittime as date) - cast(p.dob as date)) / 365.242, 2) as first_admit_age
  , CASE when ad.deathtime between ie.intime and ie.outtime THEN 1 ELSE 0 END AS mort_icu
  , CASE when ad.deathtime between ad.admittime and ad.dischtime THEN 1 ELSE 0 END AS mort_hosp
  -- here we assign labels to ITEMIDs
  -- this also fuses together multiple ITEMIDs containing the same data
  , CASE
        when le.itemid = 50868 then 'ANION GAP'
        when le.itemid = 50862 then 'ALBUMIN'
        when le.itemid = 50882 then 'BICARBONATE'
        when le.itemid = 50885 then 'BILIRUBIN'
        when le.itemid = 50912 then 'CREATININE'
        when le.itemid = 50806 then 'CHLORIDE'
        when le.itemid = 50902 then 'CHLORIDE'
        when itemid = 50809 then 'GLUCOSE'
        when itemid = 50931 then 'GLUCOSE'
        when itemid = 50810 then 'HEMATOCRIT'
        when itemid = 51221 then 'HEMATOCRIT'
        when itemid = 50811 then 'HEMOGLOBIN'
        when itemid = 51222 then 'HEMOGLOBIN'
        when itemid = 50813 then 'LACTATE'
        when itemid = 50960 then 'MAGNESIUM'
        when itemid = 50970 then 'PHOSPHATE'
        when itemid = 51265 then 'PLATELET'
        when itemid = 50822 then 'POTASSIUM'
        when itemid = 50971 then 'POTASSIUM'
        when itemid = 51275 then 'PTT'
        when itemid = 51237 then 'INR'
        when itemid = 51274 then 'PT'
        when itemid = 50824 then 'SODIUM'
        when itemid = 50983 then 'SODIUM'
        when itemid = 51006 then 'BUN'
        when itemid = 51300 then 'WBC'
        when itemid = 51301 then 'WBC'
        -- Calcium
        when itemid = 50893 then 'CALCIUM'
        -- Free calcium
        when itemid = 50808 then 'FREECALCIUM'
      ELSE null
      END AS label
  , -- add in some sanity checks on the values
    -- the where clause below requires all valuenum to be > 0,
    -- so these are only upper limit checks
    CASE
      when le.itemid = 50862 and le.valuenum >    10 then null -- g/dL 'ALBUMIN'
      when le.itemid = 50868 and le.valuenum > 10000 then null -- mEq/L 'ANION GAP'
      when le.itemid = 50882 and le.valuenum > 10000 then null -- mEq/L 'BICARBONATE'
      when le.itemid = 50885 and le.valuenum >   150 then null -- mg/dL 'BILIRUBIN'
      when le.itemid = 50806 and le.valuenum > 10000 then null -- mEq/L 'CHLORIDE'
      when le.itemid = 50902 and le.valuenum > 10000 then null -- mEq/L 'CHLORIDE'
      when le.itemid = 50912 and le.valuenum >   150 then null -- mg/dL 'CREATININE'
      when le.itemid = 50809 and le.valuenum > 10000 then null -- mg/dL 'GLUCOSE'
      when le.itemid = 50931 and le.valuenum > 10000 then null -- mg/dL 'GLUCOSE'
      when le.itemid = 50810 and le.valuenum >   100 then null -- % 'HEMATOCRIT'
      when le.itemid = 51221 and le.valuenum >   100 then null -- % 'HEMATOCRIT'
      when le.itemid = 50811 and le.valuenum >    50 then null -- g/dL 'HEMOGLOBIN'
      when le.itemid = 51222 and le.valuenum >    50 then null -- g/dL 'HEMOGLOBIN'
      when le.itemid = 50813 and le.valuenum >    50 then null -- mmol/L 'LACTATE'
      when le.itemid = 50960 and le.valuenum >    60 then null -- mmol/L 'MAGNESIUM'
      when le.itemid = 50970 and le.valuenum >    60 then null -- mg/dL 'PHOSPHATE'
      when le.itemid = 51265 and le.valuenum > 10000 then null -- K/uL 'PLATELET'
      when le.itemid = 50822 and le.valuenum >    30 then null -- mEq/L 'POTASSIUM'
      when le.itemid = 50971 and le.valuenum >    30 then null -- mEq/L 'POTASSIUM'
      when le.itemid = 51275 and le.valuenum >   150 then null -- sec 'PTT'
      when le.itemid = 51237 and le.valuenum >    50 then null -- 'INR'
      when le.itemid = 51274 and le.valuenum >   150 then null -- sec 'PT'
      when le.itemid = 50824 and le.valuenum >   200 then null -- mEq/L == mmol/L 'SODIUM'
      when le.itemid = 50983 and le.valuenum >   200 then null -- mEq/L == mmol/L 'SODIUM'
      when le.itemid = 51006 and le.valuenum >   300 then null -- 'BUN'
      when le.itemid = 51300 and le.valuenum >  1000 then null -- 'WBC'
      when le.itemid = 51301 and le.valuenum >  1000 then null -- 'WBC'
      -- Calcium
      when le.itemid = 50893 and le.valuenum > 300 then null
      -- Free Calcium
      when le.itemid = 50808 and le.valuenum > 500 then null
    ELSE le.valuenum
    END AS valuenum
  FROM icustays ie

  LEFT JOIN labevents le
    ON le.subject_id = ie.subject_id
    AND le.hadm_id = ie.hadm_id
    AND le.charttime between (ie.intime - interval '24' hour)
    AND (ie.intime + interval '24' hour)
    AND le.itemid IN
    (
      -- comment is: LABEL | CATEGORY | FLUID | NUMBER OF ROWS IN LABEVENTS
      50868, -- ANION GAP | CHEMISTRY | BLOOD | 769895
      50862, -- ALBUMIN | CHEMISTRY | BLOOD | 146697
      50882, -- BICARBONATE | CHEMISTRY | BLOOD | 780733
      50885, -- BILIRUBIN, TOTAL | CHEMISTRY | BLOOD | 238277
      50912, -- CREATININE | CHEMISTRY | BLOOD | 797476
      50902, -- CHLORIDE | CHEMISTRY | BLOOD | 795568
      50806, -- CHLORIDE, WHOLE BLOOD | BLOOD GAS | BLOOD | 48187
      50931, -- GLUCOSE | CHEMISTRY | BLOOD | 748981
      50809, -- GLUCOSE | BLOOD GAS | BLOOD | 196734
      51221, -- HEMATOCRIT | HEMATOLOGY | BLOOD | 881846
      50810, -- HEMATOCRIT, CALCULATED | BLOOD GAS | BLOOD | 89715
      51222, -- HEMOGLOBIN | HEMATOLOGY | BLOOD | 752523
      50811, -- HEMOGLOBIN | BLOOD GAS | BLOOD | 89712
      50813, -- LACTATE | BLOOD GAS | BLOOD | 187124
      50960, -- MAGNESIUM | CHEMISTRY | BLOOD | 664191
      50970, -- PHOSPHATE | CHEMISTRY | BLOOD | 590524
      51265, -- PLATELET COUNT | HEMATOLOGY | BLOOD | 778444
      50971, -- POTASSIUM | CHEMISTRY | BLOOD | 845825
      50822, -- POTASSIUM, WHOLE BLOOD | BLOOD GAS | BLOOD | 192946
      51275, -- PTT | HEMATOLOGY | BLOOD | 474937
      51237, -- INR(PT) | HEMATOLOGY | BLOOD | 471183
      51274, -- PT | HEMATOLOGY | BLOOD | 469090
      50983, -- SODIUM | CHEMISTRY | BLOOD | 808489
      50824, -- SODIUM, WHOLE BLOOD | BLOOD GAS | BLOOD | 71503
      51006, -- UREA NITROGEN | CHEMISTRY | BLOOD | 791925
      51301, -- WHITE BLOOD CELLS | HEMATOLOGY | BLOOD | 753301
      51300,  -- WBC COUNT | HEMATOLOGY | BLOOD | 2371
      -- calcium total
      50893, -- CALCIUM TOTAL | NA | NA | NA
      -- Free calcium
      50808  --FREE CALCIUM | NA | NA | NA
    )
    AND le.valuenum IS NOT null
    AND le.valuenum > 0 -- lab values cannot be 0 and cannot be negative

    LEFT JOIN admissions ad
    ON ie.subject_id = ad.subject_id
    AND ie.hadm_id = ad.hadm_id

    INNER JOIN patients p
    ON ie.subject_id = p.subject_id
    WHERE ROUND((cast(ad.admittime as date) - cast(p.dob as date)) / 365.242, 2) > 15
    -- WHERE ie.subject_id < 10000

),
ranked AS (
SELECT pvt.*, DENSE_RANK() OVER (PARTITION BY
    pvt.subject_id, pvt.hadm_id,pvt.icustay_id,pvt.label ORDER BY cast(pvt.charttime as date)) as drank
FROM pvt
)
SELECT r.subject_id, r.hadm_id, r.icustay_id, r.mort_icu, r.mort_hosp
  -- , max(r.hadm_id) as HADM_ID
  -- , max(r.icustay_id) as ICUSTAY_ID
  , max(r.los) as LOS
  , max(r.mort_icu) as MORT_ICU
  , max(r.mort_hosp) as MORT_HOSP
  , max(r.first_admit_age) as FIRST_ADMIT_AGE
  , max(r.charttime) as CHARTTIME
  , max(case when label = 'ANION GAP' then valuenum else null end) as ANIONGAP_1st
  , max(case when label = 'ALBUMIN' then valuenum else null end) as ALBUMIN_1st
  , max(case when label = 'BICARBONATE' then valuenum else null end) as BICARBONATE_1st
  , max(case when label = 'BILIRUBIN' then valuenum else null end) as BILIRUBIN_1st
  , max(case when label = 'CREATININE' then valuenum else null end) as CREATININE_1st
  , max(case when label = 'CHLORIDE' then valuenum else null end) as CHLORIDE_1st
  , max(case when label = 'GLUCOSE' then valuenum else null end) as GLUCOSE_1st
  , max(case when label = 'HEMATOCRIT' then valuenum else null end) as HEMATOCRIT_1st
  , max(case when label = 'HEMOGLOBIN' then valuenum else null end) as HEMOGLOBIN_1st
  , max(case when label = 'LACTATE' then valuenum else null end) as LACTATE_1st
  , max(case when label = 'MAGNESIUM' then valuenum else null end) as MAGNESIUM_1st
  , max(case when label = 'PHOSPHATE' then valuenum else null end) as PHOSPHATE_1st
  , max(case when label = 'PLATELET' then valuenum else null end) as PLATELET_1st
  , max(case when label = 'POTASSIUM' then valuenum else null end) as POTASSIUM_1st
  , max(case when label = 'PTT' then valuenum else null end) as PTT_1st
  , max(case when label = 'INR' then valuenum else null end) as INR_1st
  , max(case when label = 'PT' then valuenum else null end) as PT_1st
  , max(case when label = 'SODIUM' then valuenum else null end) as SODIUM_1st
  , max(case when label = 'BUN' then valuenum else null end) as BUN_1st
  , max(case when label = 'WBC' then valuenum else null end) as WBC_1st
  -- Calcium
  , max(case when label = 'CALCIUM' then valuenum else null end) as CALCIUM_1st
  , max(case when label = 'FREECALCIUM' then valuenum else null end) as FREECALCIUM_1st
FROM ranked r
WHERE r.drank = 1
GROUP BY r.subject_id, r.hadm_id, r.icustay_id, r.mort_icu, r.mort_hosp, r.drank
ORDER BY r.subject_id, r.hadm_id, r.icustay_id, r.mort_icu, r.mort_hosp, r.drank;
"""

data = pd.read_sql_query(query,con)

KeyboardInterrupt:

In [ ]:
print data

In [ ]:
data.to_csv('all_data_initial.csv')

#### From initial to first lab measurements (to be updated)

In [15]:
data_initial = pd.read_csv("all_data_initial.csv", index_col=0)

In [16]:
data_final = data_initial.groupby('subject_id').apply(lambda x: x.sort_values('charttime')).reset_index(drop=True)

In [17]:
print data_final

       subject_id  hadm_id  icustay_id  mort_icu  mort_hosp      los  \
0               3   145834      211552         0          0   6.0646
1               4   185777      294638         0          0   1.6785
2               6   107064      228232         0          0   3.6729
3               9   150750      220597         1          1   5.3231
4              11   194540      229441         0          0   1.5844
5              12   112213      232669         0          1   7.6348
6              13   143045      263738         0          0   3.6660
7              17   194023      277042         0          0   2.0710
8              17   161087      257980         0          0   0.8795
9              18   188822      298129         0          0   1.2885
10             19   109235      273430         0          0   1.3017
11             20   157681      264490         0          0   1.0508
12             21   109451      217847         0          0   5.9017
13             21   111970      216859         1          1   8.3647
14             22   165315      204798         0          0   1.1438
15             23   152223      227807         0          0   1.2641
16             23   124321      234044         0          0   1.1862
17             24   161859      262236         0          0   0.5124
18             25   129635      203487         0          0   3.5466
19             26   197661      244882         0          0   2.1407
20             28   162569      225559         0          0   1.1224
21             30   104557      225176         0          0   1.8472
22             31   128652      254478         1          1   7.9379
23             32   175413      295037         0          0   7.6854
24             33   176176      296681         0          0   1.5542
25             34   115799      263086         0          0   0.7198
26             34   144319      290505         0          0   1.5824
27             35   166707      282039         0          0   5.3757
28             36   182104      280987         0          0   1.1096
29             36   122659      211200         0          0   6.8595
...           ...      ...         ...       ...        ...      ...
53401       99901   131711      226541         0          0   6.1242
53402       99903   135939      291066         0          0   1.0388
53403       99912   189380      236183         0          0  12.0867
53404       99913   175989      292375         0          0   3.1669
53405       99922   123563      259919         0          0   1.0023
53406       99923   164914      202505         0          0   0.7497
53407       99923   192053      298857         0          0   2.2353
53408       99928   104802      236704         0          0   0.9902
53409       99934   176121      291007         0          0   3.5489
53410       99935   174624      255381         1          1   0.6598
53411       99936   107913      213906         0          0   3.8185
53412       99937   129380      291004         0          0   1.1816
53413       99938   103815      296707         0          0   7.2813
53414       99939   159023      252442         0          0   2.8780
53415       99944   185654      221067         0          0   4.0542
53416       99946   157197      298613         0          0   0.7992
53417       99955   108494      243255         1          1   5.6719
53418       99957   148574      257127         0          0   2.8684
53419       99965   101083      257338         0          0   1.7262
53420       99966   167228      252173         0          0   1.7034
53421       99973   150202      275083         0          0   2.7319
53422       99982   151454      221194         0          0   7.9493
53423       99982   112748      275958         0          0   4.9427
53424       99982   183791      239827         0          0   6.1701
53425       99983   117390      286606         0          0   1.0399
53426       99985   176670      279638         0          0  11.2998
53427       99991   151118      226241         0          0   3.1426
53428       99992   197084      242052         0          0   1.9745
53429       99995   137810      229633         0          0   2.1615
53430       99999   113369      246512         0          0   1.1242

       mort_icu.1  mort_hosp.1  first_admit_age            charttime  \
0               0            0            76.52  2101-10-20 21:51:00
1               0            0            47.84  2191-03-16 05:42:00
2               0            0            65.94  2175-05-30 22:56:00
3               1            1            41.79  2149-11-10 09:40:00
4               0            0            50.15  2178-04-17 02:35:00
5               0            1            72.37  2104-08-07 23:55:00
6               0            0            39.86  2167-01-09 17:14:00
7               0            0            47.45  2134-12-28 13:58:00
8               0            0            47.82  2135-05-09 20:52:00
9               0            0            50.84  2167-10-02 10:44:00
10              0            0           300.00  2108-08-05 15:00:00
11              0            0            75.88  2183-04-29 13:23:00
12              0            0            87.44  2134-09-12 20:13:00
13              1            1            87.82  2135-01-31 05:20:00
14              0            0            64.93  2196-04-09 10:14:00
15              0            0            71.13  2153-09-04 01:27:00
16              0            0            75.25  2157-10-21 13:40:00
17              0            0            39.02  2139-06-07 03:00:00
18              0            0            58.95  2160-11-02 23:18:00
19              0            0            72.00  2126-05-08 04:00:00
20              0            0            74.38  2177-09-02 02:00:00
21              0            0           300.00  2172-10-15 04:00:00
22              1            1            72.26  2108-08-23 16:12:00
23              0            0            45.51  2170-04-04 18:54:00
24              0            0            82.39  2116-12-23 23:53:00
25              0            0           300.00  2186-07-18 18:12:00
26              0            0           304.60  2191-02-23 10:48:00
27              0            0            69.44  2122-02-11 01:17:00
28              0            0            69.70  2131-05-05 01:44:00
29              0            0            69.73  2131-05-17 06:09:00
...           ...          ...              ...                  ...
53401           0            0            68.83  2173-01-12 07:30:00
53402           0            0            50.11  2146-01-07 02:31:00
53403           0            0            84.54  2153-04-13 21:54:00
53404           0            0            71.09  2141-05-12 19:04:00
53405           0            0            69.28  2107-04-07 16:58:00
53406           0            0            54.39  2201-02-23 23:21:00
53407           0            0            54.61  2201-05-15 23:32:00
53408           0            0            20.87  2181-11-16 22:48:00
53409           0            0            17.95  2110-02-28 04:05:00
53410           1            1            75.57  2139-12-15 05:59:00
53411           0            0           300.00  2182-10-11 16:55:00
53412           0            0            65.68  2128-05-12 05:03:00
53413           0            0            80.84  2200-10-27 22:04:00
53414           0            0            26.95  2110-03-22 20:58:00
53415           0            0            85.48  2161-02-16 22:01:00
53416           0            0            49.67  2161-07-15 01:05:00
53417           1            1            63.19  2139-07-14 22:04:00
53418           0            0            68.05  2157-02-20 23:38:00
53419           0            0            66.29  2191-07-13 21:48:00
53420           0            0            77.49  2191-08-24 05:10:00
53421           0            0            65.50  2180-11-27 17:25:00
53422           0            0            65.16  2156-11-29 11:03:00
53423           0            0            65.26  2157-01-07 13:21:00
53424           0            0            65.38  2157-02-16 18:45:00
53425           0            0            78.58  2193-04-26 22:13:00
53426           0            0            53.81  2181-01-29 10:07:00
53427           0            0            47.72  2184-12-28 22:05:00
53428           0            0            65.77  2144-07-25 18:02:00
53429           0            0            88.70  2147-02-08 20:36:00
53430           0            0            63.98  2117-12-31 10:30:00

            ...         platelet_1st  potassium_1st  ptt_1st  inr_1st  pt_1st  \
0           ...                282.0            5.4     58.3      1.7    15.7
1           ...                207.0            3.1     31.3      1.0    12.3
2           ...                315.0            5.4    139.0      1.4    14.6
3           ...                258.0            2.9     21.7      1.1    12.7
4           ...                229.0            3.8     28.3      1.1    13.0
5           ...                349.0            4.4     82.7      1.7    15.9
6           ...                216.0            3.5     44.1      1.2    13.7
7           ...                138.0            3.9     31.8      1.5    14.9
8           ...                532.0            4.4     26.4      1.3    14.5
9           ...                227.0            4.1     30.5      1.2    13.6
10          ...                230.0            5.4     29.2      1.2    13.6
11          ...                111.0            4.6     31.3      1.6    15.7
12          ...                310.0            5.1     27.1      1.4    14.4
13          ...                275.0            3.8     31.7      1.7    18.1
14          ...                259.0            4.4     30.1      1.1    12.4
15          ...                130.0            4.1     42.0      2.0    17.5
16          ...                208.0            3.9     25.3      0.9    11.3
17          ...                215.0            4.1     22.5      1.0    12.4
18          ...                269.0            6.5     41.6      1.1    13.0
19          ...                168.0            4.7     27.2      2.5    19.4
20          ...                150.0            5.2     31.8      1.4    15.1
21          ...                211.0            4.1     43.1      1.2    13.2
22          ...                109.0            3.3     29.4      1.2    13.2
23          ...                265.0            4.7     28.1      1.2    13.1
24          ...                545.0            4.0     26.4      1.2    13.3
25          ...                299.0            4.1     25.0      1.1    12.3
26          ...                350.0            4.8     30.5      3.3    32.6
27          ...                 92.0            8.1     48.8      1.6    17.5
28          ...                149.0            6.2     40.9      1.5    16.1
29          ...                712.0            4.5     95.4      1.5    16.1
...         ...                  ...            ...      ...      ...     ...
53401       ...                147.0            3.9     78.2      2.4    25.0
53402       ...                216.0            3.1     29.2      1.1    13.0
53403       ...                270.0            4.6     23.6      1.1    13.0
53404       ...                148.0            4.6     38.4      2.0    21.2
53405       ...                119.0            5.9     30.3      1.6    16.5
53406       ...                130.0            5.2      NaN      1.2    14.3
53407       ...                162.0            4.4     49.1      4.7    44.8
53408       ...                379.0            5.0      NaN      NaN     NaN
53409       ...                543.0            5.1     30.9      1.4    15.9
53410       ...                197.0            3.6     25.7      1.2    13.5
53411       ...                343.0            4.5     59.4      1.2    13.9
53412       ...                246.0            5.0     20.6      1.1    12.5
53413       ...                247.0            5.2     51.2      1.6    17.9
53414       ...                129.0            5.3     73.5      1.2    14.2
53415       ...                311.0            3.4     26.0      1.0    12.0
53416       ...                255.0            3.2     39.0      3.0    30.9
53417       ...                176.0            5.2     22.4      1.1    13.2
53418       ...                399.0            4.0     33.9      1.3    15.2
53419       ...                330.0            4.4     22.6      1.5    16.8
53420       ...                185.0            4.9     25.8      1.1    12.5
53421       ...                323.0            3.5     29.2      1.3    14.6
53422       ...                113.0            3.8     31.4      1.3    14.7
53423       ...                139.0            4.0     38.1      2.2    23.4
53424       ...                163.0            3.8     34.3      1.3    13.9
53425       ...                253.0            4.5     27.0      1.1    13.4
53426       ...                247.0            4.3     39.5      1.1    13.3
53427       ...                256.0            4.1     34.2      1.3    14.6
53428       ...                188.0            4.9     43.9      1.1    12.9
53429       ...                189.0            4.1     35.5      1.9    19.7
53430       ...                252.0            4.2      NaN      NaN     NaN

       sodium_1st  bun_1st  wbc_1st  calcium_1st  freecalcium_1st
0           153.0     53.0     19.1          8.2             1.09
1           135.0      9.0      9.7          8.9              NaN
2           138.0     62.0     10.6          8.6             1.27
3           140.0     16.0      7.5          9.2             0.99
4           138.0     12.0      8.5          9.6              NaN
5           141.0     30.0     12.9          8.2             1.20
6           139.0     13.0     16.6          8.9             1.34
7           139.0     11.0     10.5          NaN             1.32
8           139.0     17.0     24.9          NaN             1.22
9           136.0     11.0     10.4          9.5             1.16
10          138.0     33.0     14.8          9.2              NaN
11          143.0     18.0     17.5          8.1             1.18
12          140.0     94.0     17.5          9.5             1.27
13          137.0     49.0     30.5          7.7              NaN
14          140.0     17.0      5.1          9.1              NaN
15          140.0     15.0      7.6          8.0             1.21
16          144.0     18.0     14.8          8.7             1.07
17          139.0     13.0      9.8          9.3              NaN
18          139.0     54.0     13.0          8.2             1.17
19          143.0     33.0      8.2          8.5              NaN
20          137.0     17.0      6.9          8.0             1.20
21          129.0     46.0     14.1          9.0              NaN
22          128.0     13.0      6.9          8.2             1.12
23          143.0     11.0     16.4          7.8             0.99
24          137.0     21.0     33.5          7.9              NaN
25          140.0     29.0     11.1          8.9              NaN
26          143.0     38.0      7.3          8.4             1.10
27          141.0     11.0     13.8          NaN             1.25
28          137.0     12.0     18.8          8.1             1.21
29          133.0     29.0     20.4          8.3             1.01
...           ...      ...      ...          ...              ...
53401       129.0     49.0      7.5          8.8              NaN
53402       143.0     13.0      5.1          8.7              NaN
53403       140.0     26.0      3.7          9.3             1.05
53404       139.0     16.0      9.7          NaN             1.24
53405       140.0      9.0     12.0          NaN             1.16
53406       120.0     78.0      8.4          7.9              NaN
53407       129.0     76.0      9.1          9.3             1.11
53408       133.0     19.0     11.6          8.5              NaN
53409       137.0     11.0     18.0          8.2              NaN
53410       143.0     25.0     19.4          9.2             1.13
53411       141.0     39.0      5.4          8.9             1.11
53412       136.0     11.0     11.6          8.4              NaN
53413       131.0     36.0     11.9          8.8             1.18
53414       148.0    162.0     12.7          7.8             0.95
53415       141.0     31.0     15.0          8.6              NaN
53416       142.0     22.0     16.5          9.8              NaN
53417       148.0     19.0     14.7          9.3             1.08
53418       133.0     15.0     14.5          8.5             1.12
53419       135.0     17.0     15.8          9.0              NaN
53420       135.0     21.0     11.0          9.0              NaN
53421       140.0     21.0     17.2          7.4              NaN
53422       137.0     29.0      3.8          8.8             1.14
53423       139.0     46.0      6.0          8.9              NaN
53424       131.0     42.0      7.1          9.3              NaN
53425       139.0     16.0      7.5          9.4              NaN
53426       134.0     18.0     19.4          8.0              NaN
53427       139.0     30.0      3.3          8.6              NaN
53428       136.0     56.0     21.4          7.1              NaN
53429       139.0     10.0      8.2          8.5             1.12
53430       138.0     32.0     12.4          7.9              NaN

[53431 rows x 32 columns]

In [18]:
data_final = data_final.groupby('subject_id').first().reset_index()

In [19]:
print data_final

       subject_id  hadm_id  icustay_id  mort_icu  mort_hosp      los  \
0               3   145834      211552         0          0   6.0646
1               4   185777      294638         0          0   1.6785
2               6   107064      228232         0          0   3.6729
3               9   150750      220597         1          1   5.3231
4              11   194540      229441         0          0   1.5844
5              12   112213      232669         0          1   7.6348
6              13   143045      263738         0          0   3.6660
7              17   194023      277042         0          0   2.0710
8              18   188822      298129         0          0   1.2885
9              19   109235      273430         0          0   1.3017
10             20   157681      264490         0          0   1.0508
11             21   109451      217847         0          0   5.9017
12             22   165315      204798         0          0   1.1438
13             23   152223      227807         0          0   1.2641
14             24   161859      262236         0          0   0.5124
15             25   129635      203487         0          0   3.5466
16             26   197661      244882         0          0   2.1407
17             28   162569      225559         0          0   1.1224
18             30   104557      225176         0          0   1.8472
19             31   128652      254478         1          1   7.9379
20             32   175413      295037         0          0   7.6854
21             33   176176      296681         0          0   1.5542
22             34   115799      263086         0          0   0.7198
23             35   166707      282039         0          0   5.3757
24             36   182104      280987         0          0   1.1096
25             37   188670      213503         0          0   1.1397
26             38   185910      248910         0          0  25.5485
27             41   101757      261027         0          0   3.3937
28             42   119203      210828         0          0   1.9024
29             43   146828      225852         0          0   4.6252
...           ...      ...         ...       ...        ...      ...
38575       99894   127380      204236         0          0   3.7134
38576       99897   162913      266801         0          0   1.6097
38577       99899   188409      245756         1          1   9.1439
38578       99901   131711      226541         0          0   6.1242
38579       99903   135939      291066         0          0   1.0388
38580       99912   189380      236183         0          0  12.0867
38581       99913   175989      292375         0          0   3.1669
38582       99922   123563      259919         0          0   1.0023
38583       99923   164914      202505         0          0   0.7497
38584       99928   104802      236704         0          0   0.9902
38585       99934   176121      291007         0          0   3.5489
38586       99935   174624      255381         1          1   0.6598
38587       99936   107913      213906         0          0   3.8185
38588       99937   129380      291004         0          0   1.1816
38589       99938   103815      296707         0          0   7.2813
38590       99939   159023      252442         0          0   2.8780
38591       99944   185654      221067         0          0   4.0542
38592       99946   157197      298613         0          0   0.7992
38593       99955   108494      243255         1          1   5.6719
38594       99957   148574      257127         0          0   2.8684
38595       99965   101083      257338         0          0   1.7262
38596       99966   167228      252173         0          0   1.7034
38597       99973   150202      275083         0          0   2.7319
38598       99982   151454      221194         0          0   7.9493
38599       99983   117390      286606         0          0   1.0399
38600       99985   176670      279638         0          0  11.2998
38601       99991   151118      226241         0          0   3.1426
38602       99992   197084      242052         0          0   1.9745
38603       99995   137810      229633         0          0   2.1615
38604       99999   113369      246512         0          0   1.1242

       mort_icu.1  mort_hosp.1  first_admit_age            charttime  \
0               0            0            76.52  2101-10-20 21:51:00
1               0            0            47.84  2191-03-16 05:42:00
2               0            0            65.94  2175-05-30 22:56:00
3               1            1            41.79  2149-11-10 09:40:00
4               0            0            50.15  2178-04-17 02:35:00
5               0            1            72.37  2104-08-07 23:55:00
6               0            0            39.86  2167-01-09 17:14:00
7               0            0            47.45  2134-12-28 13:58:00
8               0            0            50.84  2167-10-02 10:44:00
9               0            0           300.00  2108-08-05 15:00:00
10              0            0            75.88  2183-04-29 13:23:00
11              0            0            87.44  2134-09-12 20:13:00
12              0            0            64.93  2196-04-09 10:14:00
13              0            0            71.13  2153-09-04 01:27:00
14              0            0            39.02  2139-06-07 03:00:00
15              0            0            58.95  2160-11-02 23:18:00
16              0            0            72.00  2126-05-08 04:00:00
17              0            0            74.38  2177-09-02 02:00:00
18              0            0           300.00  2172-10-15 04:00:00
19              1            1            72.26  2108-08-23 16:12:00
20              0            0            45.51  2170-04-04 18:54:00
21              0            0            82.39  2116-12-23 23:53:00
22              0            0           300.00  2186-07-18 18:12:00
23              0            0            69.44  2122-02-11 01:17:00
24              0            0            69.70  2131-05-05 01:44:00
25              0            0            68.93  2183-08-23 23:00:00
26              0            0            75.94  2166-08-11 00:01:00
27              0            0            56.63  2133-01-04 01:44:00
28              0            0            61.16  2116-04-26 20:00:00
29              0            0            32.77  2186-10-02 14:10:00
...           ...          ...              ...                  ...
38575           0            0            60.00  2129-07-05 14:16:00
38576           0            0            53.55  2181-08-06 23:08:00
38577           1            1            86.96  2113-06-04 21:27:00
38578           0            0            68.83  2173-01-12 07:30:00
38579           0            0            50.11  2146-01-07 02:31:00
38580           0            0            84.54  2153-04-13 21:54:00
38581           0            0            71.09  2141-05-12 19:04:00
38582           0            0            69.28  2107-04-07 16:58:00
38583           0            0            54.39  2201-02-23 23:21:00
38584           0            0            20.87  2181-11-16 22:48:00
38585           0            0            17.95  2110-02-28 04:05:00
38586           1            1            75.57  2139-12-15 05:59:00
38587           0            0           300.00  2182-10-11 16:55:00
38588           0            0            65.68  2128-05-12 05:03:00
38589           0            0            80.84  2200-10-27 22:04:00
38590           0            0            26.95  2110-03-22 20:58:00
38591           0            0            85.48  2161-02-16 22:01:00
38592           0            0            49.67  2161-07-15 01:05:00
38593           1            1            63.19  2139-07-14 22:04:00
38594           0            0            68.05  2157-02-20 23:38:00
38595           0            0            66.29  2191-07-13 21:48:00
38596           0            0            77.49  2191-08-24 05:10:00
38597           0            0            65.50  2180-11-27 17:25:00
38598           0            0            65.16  2156-11-29 11:03:00
38599           0            0            78.58  2193-04-26 22:13:00
38600           0            0            53.81  2181-01-29 10:07:00
38601           0            0            47.72  2184-12-28 22:05:00
38602           0            0            65.77  2144-07-25 18:02:00
38603           0            0            88.70  2147-02-08 20:36:00
38604           0            0            63.98  2117-12-31 10:30:00

            ...         platelet_1st  potassium_1st  ptt_1st  inr_1st  pt_1st  \
0           ...                282.0            5.4     58.3      1.7    15.7
1           ...                207.0            3.1     31.3      1.0    12.3
2           ...                315.0            5.4    139.0      1.4    14.6
3           ...                258.0            2.9     21.7      1.1    12.7
4           ...                229.0            3.8     28.3      1.1    13.0
5           ...                349.0            4.4     82.7      1.7    15.9
6           ...                216.0            3.5     44.1      1.2    13.7
7           ...                138.0            3.9     31.8      1.5    14.9
8           ...                227.0            4.1     30.5      1.2    13.6
9           ...                230.0            5.4     29.2      1.2    13.6
10          ...                111.0            4.6     31.3      1.6    15.7
11          ...                310.0            5.1     27.1      1.4    14.4
12          ...                259.0            4.4     30.1      1.1    12.4
13          ...                130.0            4.1     42.0      2.0    17.5
14          ...                215.0            4.1     22.5      1.0    12.4
15          ...                269.0            6.5     41.6      1.1    13.0
16          ...                168.0            4.7     27.2      2.5    19.4
17          ...                150.0            5.2     31.8      1.4    15.1
18          ...                211.0            4.1     43.1      1.2    13.2
19          ...                109.0            3.3     29.4      1.2    13.2
20          ...                265.0            4.7     28.1      1.2    13.1
21          ...                545.0            4.0     26.4      1.2    13.3
22          ...                299.0            4.1     25.0      1.1    12.3
23          ...                 92.0            8.1     48.8      1.6    17.5
24          ...                149.0            6.2     40.9      1.5    16.1
25          ...                263.0            4.0     24.6      1.2    13.3
26          ...                 76.0            4.4     50.6      1.7    15.6
27          ...                189.0            3.8     23.7      0.9    11.5
28          ...                228.0            4.3     25.7      1.6    15.4
29          ...                305.0            4.7     24.6      1.0    11.9
...         ...                  ...            ...      ...      ...     ...
38575       ...                277.0            4.3     24.4      1.0    11.9
38576       ...                505.0            5.0      NaN      NaN     NaN
38577       ...                232.0            5.7     30.7      1.2    13.7
38578       ...                147.0            3.9     78.2      2.4    25.0
38579       ...                216.0            3.1     29.2      1.1    13.0
38580       ...                270.0            4.6     23.6      1.1    13.0
38581       ...                148.0            4.6     38.4      2.0    21.2
38582       ...                119.0            5.9     30.3      1.6    16.5
38583       ...                130.0            5.2     49.1      1.2    14.3
38584       ...                379.0            5.0      NaN      NaN     NaN
38585       ...                543.0            5.1     30.9      1.4    15.9
38586       ...                197.0            3.6     25.7      1.2    13.5
38587       ...                343.0            4.5     59.4      1.2    13.9
38588       ...                246.0            5.0     20.6      1.1    12.5
38589       ...                247.0            5.2     51.2      1.6    17.9
38590       ...                129.0            5.3     73.5      1.2    14.2
38591       ...                311.0            3.4     26.0      1.0    12.0
38592       ...                255.0            3.2     39.0      3.0    30.9
38593       ...                176.0            5.2     22.4      1.1    13.2
38594       ...                399.0            4.0     33.9      1.3    15.2
38595       ...                330.0            4.4     22.6      1.5    16.8
38596       ...                185.0            4.9     25.8      1.1    12.5
38597       ...                323.0            3.5     29.2      1.3    14.6
38598       ...                113.0            3.8     31.4      1.3    14.7
38599       ...                253.0            4.5     27.0      1.1    13.4
38600       ...                247.0            4.3     39.5      1.1    13.3
38601       ...                256.0            4.1     34.2      1.3    14.6
38602       ...                188.0            4.9     43.9      1.1    12.9
38603       ...                189.0            4.1     35.5      1.9    19.7
38604       ...                252.0            4.2      NaN      NaN     NaN

       sodium_1st  bun_1st  wbc_1st  calcium_1st  freecalcium_1st
0           153.0     53.0     19.1          8.2             1.09
1           135.0      9.0      9.7          8.9              NaN
2           138.0     62.0     10.6          8.6             1.27
3           140.0     16.0      7.5          9.2             0.99
4           138.0     12.0      8.5          9.6              NaN
5           141.0     30.0     12.9          8.2             1.20
6           139.0     13.0     16.6          8.9             1.34
7           139.0     11.0     10.5          NaN             1.32
8           136.0     11.0     10.4          9.5             1.16
9           138.0     33.0     14.8          9.2              NaN
10          143.0     18.0     17.5          8.1             1.18
11          140.0     94.0     17.5          9.5             1.27
12          140.0     17.0      5.1          9.1              NaN
13          140.0     15.0      7.6          8.0             1.21
14          139.0     13.0      9.8          9.3              NaN
15          139.0     54.0     13.0          8.2             1.17
16          143.0     33.0      8.2          8.5              NaN
17          137.0     17.0      6.9          8.0             1.20
18          129.0     46.0     14.1          9.0              NaN
19          128.0     13.0      6.9          8.2             1.12
20          143.0     11.0     16.4          7.8             0.99
21          137.0     21.0     33.5          7.9              NaN
22          140.0     29.0     11.1          8.9             1.10
23          141.0     11.0     13.8          NaN             1.25
24          137.0     12.0     18.8          8.1             1.21
25          139.0     37.0     10.4          8.6              NaN
26          140.0     55.0     18.2          8.4              NaN
27          137.0     18.0      4.5          7.4             1.17
28          139.0     18.0      7.9          8.8              NaN
29          143.0     17.0     16.9          7.5              NaN
...           ...      ...      ...          ...              ...
38575       142.0     45.0     10.9          8.4              NaN
38576       134.0     76.0     12.1          9.3              NaN
38577       125.0     42.0     11.4          9.0             1.16
38578       129.0     49.0      7.5          8.8              NaN
38579       143.0     13.0      5.1          8.7              NaN
38580       140.0     26.0      3.7          9.3             1.05
38581       139.0     16.0      9.7          NaN             1.24
38582       140.0      9.0     12.0          NaN             1.16
38583       120.0     78.0      8.4          7.9             1.11
38584       133.0     19.0     11.6          8.5              NaN
38585       137.0     11.0     18.0          8.2              NaN
38586       143.0     25.0     19.4          9.2             1.13
38587       141.0     39.0      5.4          8.9             1.11
38588       136.0     11.0     11.6          8.4              NaN
38589       131.0     36.0     11.9          8.8             1.18
38590       148.0    162.0     12.7          7.8             0.95
38591       141.0     31.0     15.0          8.6              NaN
38592       142.0     22.0     16.5          9.8              NaN
38593       148.0     19.0     14.7          9.3             1.08
38594       133.0     15.0     14.5          8.5             1.12
38595       135.0     17.0     15.8          9.0              NaN
38596       135.0     21.0     11.0          9.0              NaN
38597       140.0     21.0     17.2          7.4              NaN
38598       137.0     29.0      3.8          8.8             1.14
38599       139.0     16.0      7.5          9.4              NaN
38600       134.0     18.0     19.4          8.0              NaN
38601       139.0     30.0      3.3          8.6              NaN
38602       136.0     56.0     21.4          7.1              NaN
38603       139.0     10.0      8.2          8.5             1.12
38604       138.0     32.0     12.4          7.9              NaN

[38605 rows x 32 columns]

In [21]:
data_final.to_csv('all_data_final.csv')

In [22]:
con = psycopg2.connect(dbname=dbname, user=sqluser, password='mimic')
cur = con.cursor()
cur.execute('SET search_path to ' + schema_name)

query = \
"""
SELECT VALUEUOM FROM labevents le
WHERE le.itemid = 50808
"""

units = pd.read_sql_query(query,con)
print units

       valueuom
0        mmol/L
1        mmol/L
2        mmol/L
3        mmol/L
4        mmol/L
5        mmol/L
6        mmol/L
7        mmol/L
8        mmol/L
9        mmol/L
10       mmol/L
11       mmol/L
12       mmol/L
13       mmol/L
14       mmol/L
15       mmol/L
16       mmol/L
17       mmol/L
18       mmol/L
19       mmol/L
20       mmol/L
21       mmol/L
22       mmol/L
23       mmol/L
24       mmol/L
25       mmol/L
26       mmol/L
27       mmol/L
28       mmol/L
29       mmol/L
...         ...
249080   mmol/L
249081   mmol/L
249082   mmol/L
249083   mmol/L
249084   mmol/L
249085   mmol/L
249086   mmol/L
249087   mmol/L
249088   mmol/L
249089   mmol/L
249090   mmol/L
249091   mmol/L
249092   mmol/L
249093   mmol/L
249094   mmol/L
249095   mmol/L
249096   mmol/L
249097   mmol/L
249098   mmol/L
249099   mmol/L
249100   mmol/L
249101   mmol/L
249102   mmol/L
249103   mmol/L
249104   mmol/L
249105   mmol/L
249106   mmol/L
249107   mmol/L
249108   mmol/L
249109   mmol/L

[249110 rows x 1 columns]